services:
  trade-exportscore-trp:
    build:
      context: .
      target: production
    image: trade-exportscore-trp
    restart: always
    container_name: trade-exportscore-trp
    depends_on:
      - trade-exportscore-trp-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: trade-exportscore-trp-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      POSTGRES_DB: eutd-trade-exports-core-trade-exportscore-trp
      POSTGRES_HOST: ${POSTGRES_HOST:-trade-exportscore-trp-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-HiaNEA1V}
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}

  trade-exportscore-trp-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: eutd-trade-exports-core-trade-exportscore-trp
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-HiaNEA1V}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}
