variables:
  regionNumber: 6
  environment: SND
  subscriptionNumber: 1

  # KEYVAULT
  keyVaultName: $(environment)$(service)$(nc-role-infra)$(nc-resource-keyvault)$(subscriptionNumber)$(regionNumber)01

  infraResourceGroup: $(environment)$(service)$(nc-role-infra)$(nc-resource-resourcegroup)$(subscriptionNumber)$(regionNumber)01
