name: $(BuildID)

parameters:
  - name: deployFromFeature
    displayName: "Deploy from Feature Branch"
    type: boolean
    default: false

trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    include: 
      - infra/*

pr:
  branches:
    include:
      - main
  paths:
    include:
      - infra/*

resources:
  repositories:
    - repository: PipelineCommon
      name: DEFRA/ado-pipeline-common
      endpoint: DEFRA
      type: github
      ref: refs/tags/1.0.0-latest
    - repository: PipelineCommonScripts
      name: DEFRA/adp-common-scripts
      endpoint: DEFRA
      type: github
      ref: main

extends:
  template: /templates/pipelines/common-infrastructure-deploy.yaml@PipelineCommon
  parameters:
    deployFromFeature: ${{ parameters.deployFromFeature }}
    additionalRepositories: 
      - PipelineCommonScripts
    privateAgentName: "DEFRA-COMMON-ubuntu2004-SSV3"
    variableFiles:
      - /infra/vars/common.yaml@self
      - /infra/vars/{environment}.yaml@self
    regionalVariableFiles:
      - /infra/vars/regional/{environment}-{region}.yaml@self
    groupedDeployments:
      - name: TRP
        deployments:
          - name: network
            path: infra\network
            type: 'bicep'
            resourceGroupName: '$(environment)$(project)$(nc-function-network)$(nc-resource-resourcegroup)$(subscriptionNumber)$(regionNumber)01'
            scope: 'Resource Group'
          - name: flexible-server-zone
            path: infra\private-dns-zone
            type: 'bicep'
            resourceGroupName: '$(environment)$(project)$(nc-function-network)$(nc-resource-resourcegroup)$(subscriptionNumber)$(regionNumber)01'
            scope: 'Resource Group'
          - name: log-analytics-workspace
            path: infra\operational-insights
            type: bicep
            scope: 'Resource Group'
            resourceGroupName: '$(environment)$(project)$(nc-function-infrastructure)$(nc-resource-resourcegroup)$(subscriptionNumber)$(regionNumber)01'
          - name: service-bus
            path: infra\service-bus
            type: bicep
            scope: 'Resource Group'
            resourceGroupName: '$(environment)$(project)$(nc-function-infrastructure)$(nc-resource-resourcegroup)$(subscriptionNumber)$(regionNumber)01'
            postDeployScriptsList:
              - displayName: Resolve Private Endpoint IP for Service Bus
                scriptRepo: PipelineCommonScripts
                scriptPath: "PowerShellLibrary/Get-ResourcePrivateEndPointsDnsRecordsAsJson.ps1"
                ScriptArguments: >
                  -ResourceGroupName '$(environment)$(project)$(nc-function-infrastructure)$(nc-resource-resourcegroup)$(subscriptionNumber)$(regionNumber)01'
                  -ResourceName '$(environment)$(project)$(nc-function-infrastructure)$(nc_servicebus)$(subscriptionNumber)$(regionNumber)01'
              - displayName: Set DNS record for Service Bus
                scriptPath: "PowerShellLibrary/Set-PrivateDnsRecordSet.ps1"
                scriptRepo: PipelineCommonScripts
                serviceConnectionVariableName: msServiceConnectionName
                ScriptArguments: >
                  -Ttl 120
          - name: key-vault
            path: infra\key-vault
            type: bicep
            scope: 'Resource Group'
            postDeployScriptsList:
              - displayName: Resolve Private Endpoint IP for Key Vault
                scriptRepo: PipelineCommonScripts
                scriptPath: "PowerShellLibrary/Get-ResourcePrivateEndPointsDnsRecordsAsJson.ps1"
                ScriptArguments: >
                  -ResourceGroupName '$(environment)$(project)$(nc-function-infrastructure)$(nc-resource-resourcegroup)$(subscriptionNumber)$(regionNumber)01'
                  -ResourceName '$(environment)$(project)$(nc-function-infrastructure)$(nc_keyvault)$(subscriptionNumber)$(regionNumber)03'
              - displayName: Set DNS record for Key Vault
                scriptPath: "PowerShellLibrary/Set-PrivateDnsRecordSet.ps1"
                scriptRepo: PipelineCommonScripts
                serviceConnectionVariableName: msServiceConnectionName
                ScriptArguments: >
                  -Ttl 120
            resourceGroupName: '$(environment)$(project)$(nc-function-infrastructure)$(nc-resource-resourcegroup)$(subscriptionNumber)$(regionNumber)01'
          - name: container-registry
            path: infra\container-registry
            type: bicep
            scope: 'Resource Group'
            resourceGroupName: '$(environment)$(project)$(nc-function-infrastructure)$(nc-resource-resourcegroup)$(subscriptionNumber)$(regionNumber)01'
            postDeployScriptsList:
              - displayName: Resolve Private Endpoint IP for Container Registry
                scriptRepo: PipelineCommonScripts
                scriptPath: "PowerShellLibrary/Get-ResourcePrivateEndPointsDnsRecordsAsJson.ps1"
                ScriptArguments: >
                  -ResourceGroupName '$(environment)$(project)$(nc-function-infrastructure)$(nc-resource-resourcegroup)$(subscriptionNumber)$(regionNumber)01'
                  -ResourceName '$(environment)$(project)$(nc-function-infrastructure)$(nc_containerregistry)$(subscriptionNumber)$(regionNumber)01'
              - displayName: Set DNS record for Container Registry
                scriptPath: "PowerShellLibrary/Set-PrivateDnsRecordSet.ps1"
                scriptRepo: PipelineCommonScripts
                serviceConnectionVariableName: msServiceConnectionName
                ScriptArguments: >
                  -Ttl 120
          - name: managed-environment
            path: infra\managed-environment
            type: bicep
            scope: 'Resource Group'
            resourceGroupName: '$(environment)$(project)$(nc-function-infrastructure)$(nc-resource-resourcegroup)$(subscriptionNumber)$(regionNumber)01'
            postDeployScriptsList:
              - displayName: Resolve Private Endpoint IP for Container App Env
                scriptRepo: PipelineCommonScripts
                scriptPath: "PowerShellLibrary/Get-ResourcePrivateEndPointsDnsRecordsAsJson.ps1"
                ScriptArguments: >
                  -ResourceGroupName '$(environment)$(project)$(nc-function-infrastructure)$(nc-resource-resourcegroup)$(subscriptionNumber)$(regionNumber)01'
                  -ResourceName '$(environment)$(project)$(nc-function-infrastructure)$(nc_managedenvironment)$(subscriptionNumber)$(regionNumber)01'
              - displayName: Set DNS record for Container App Env
                scriptPath: "PowerShellLibrary/Set-PrivateDnsRecordSet.ps1"
                scriptRepo: PipelineCommonScripts
                serviceConnectionVariableName: msServiceConnectionName
                ScriptArguments: >
                  -Ttl 120
          - name: container-app
            path: infra\container-app
            type: bicep
            scope: 'Resource Group'
            resourceGroupName: '$(environment)$(project)$(nc-function-infrastructure)$(nc-resource-resourcegroup)$(subscriptionNumber)$(regionNumber)01'
          - name: postgresql
            path: infra\postgresql
            type: bicep
            scope: 'Resource Group'
            resourceGroupName: '$(environment)$(project)$(nc-function-infrastructure)$(nc-resource-resourcegroup)$(subscriptionNumber)$(regionNumber)01'
            postDeployScriptsList:
              - displayName: Resolve Private Endpoint IP for Postgres
                scriptRepo: PipelineCommonScripts
                scriptPath: "PowerShellLibrary/Get-ResourcePrivateEndPointsDnsRecordsAsJson.ps1"
                ScriptArguments: >
                  -ResourceGroupName '$(environment)$(project)$(nc-function-infrastructure)$(nc-resource-resourcegroup)$(subscriptionNumber)$(regionNumber)01'
                  -ResourceName '$(environmentLower)$(project-lower)$(nc-function-database-lower)$(nc-resource-postgres)$(subscriptionNumber)$(regionNumber)01'
              - displayName: Set DNS record for Postgres
                scriptPath: "PowerShellLibrary/Set-PrivateDnsRecordSet.ps1"
                scriptRepo: PipelineCommonScripts
                serviceConnectionVariableName: msServiceConnectionName
                ScriptArguments: >
                  -Ttl 120  

    environments:
      - name: dev1
        serviceConnection: AZR-EXP-DEV1
        deploymentBranches:
          - "refs/heads/main"
        developmentEnvironment: true
        privateAgentName: "DEFRA-COMMON-ubuntu2004-SSV3"
        azureRegions:
          primary: "UKSouth"
      - name: snd1
        dependsOn: dev1
        serviceConnection: AZR-EXP-SND1
        deploymentBranches:
          - "refs/heads/main"
        privateAgentName: "DEFRA-COMMON-ubuntu2004-SSV3"
        azureRegions:
          primary: "UKSouth"
      - name: pre1
        dependsOn: snd1
        serviceConnection: AZR-EXP-PRE1
        deploymentBranches:
          - "refs/heads/main"
        privateAgentName: "DEFRA-COMMON-ubuntu2004-SSV5"
        azureRegions:
          primary: "UKSouth"
      - name: prd1
        dependsOn: pre1
        serviceConnection: AZR-EXP-PRD1
        deploymentBranches:
          - "refs/heads/main"
        privateAgentName: "DEFRA-COMMON-ubuntu2004-SSV5"
        azureRegions:
          primary: "UKSouth"
