variables:
  # TAGS TODO: check these
  serviceCodeTag: TRP
  serviceNameTag: Trader Risk Profile
  serviceTypeTag: LOB
  createdDateTag: 20240611
  secEnvironment: SEC

  # RESOURCE NAMING CONVENTIONS
  nc-function-network: NET
  nc-function-infrastructure: INF

  nc-resource-appgateway: AG
  nc-resource-publicip: PU
  nc-resource-subnet: SU
  nc-resource-virtualnetwork: VN
  nc-resource-nsg: NS
  nc-resource-resourcegroup: RG
  nc-resource-keyvault: KV
  nc-resource-loganalytics: WS
