variables:
  environment: DEV

  # KEYVAULT
  keyVaultSku: Standard
  servicePrincipalObjectId: a4edf622-b4a6-4f58-80ea-44b05b0f05b0

  # SERVICE CONNECTION
  azureResourceManagerConnection: AZR-EXP-DEV1
  azureSubscription: AZR-EXP-DEV1
  subscriptionId: c90161c2-e11d-4a5e-9033-827da188b2ad
  tenantId: 770a2450-0227-4c62-90c7-4e38537f1102

  # DATABASE
  postgreSqlTier: "GeneralPurpose"
  postgreSqlSkuName: "Standard_D4ds_v5"
  postgreSqlStorageSizeGB: 128
  postgreSqlHighAvailability: "Disabled"
  postgreSqlAvailabilityZone: ""
  postgreSqlAdministratorUserName: "pi0zgdto4jvww4rtm9tnnyxda"

  # LOG ANALYICS
  logAnalyticsSku: 'PerGB2018'
