variables:
  regionNumber: 4
  environment: SND
  subscriptionNumber: 1

  # KEYVAULT
  keyVaultSku: Standard
  servicePrincipalObjectId: 15f55f6e-a7ec-4efa-919b-673666a0a65b

  # SERVICE CONNECTION
  azureResourceManagerConnection: AZR-EXP-SND1
  azureSubscription: AZR-EXP-SND1
  subscriptionId: 9f93a159-97af-42db-9041-6426ae76c837
  tenantId: 770a2450-0227-4c62-90c7-4e38537f1102

  # DATABASE
  postgreSqlTier: "GeneralPurpose"
  postgreSqlSkuName: "Standard_D4ds_v5"
  postgreSqlStorageSizeGB: 128
  postgreSqlHighAvailability: "Disabled"
  postgreSqlAvailabilityZone: ""
  postgreSqlAdministratorUserName: "m667gln3w55z0lu35r649ov3z"

  # LOG ANALYICS
  logAnalyticsSku: 'PerGB2018'
