parameters:
  - name: forceDevDeploy
    displayName: Force deployment to DEV
    type: boolean
    default: false
  - name: environments
    type: object
    default:
      - "dev"
      - "snd"
      - "pre"
      - "prd"
  - name: deployToSecondary
    type: string
    default: ""
  - name: azureRegions
    type: object
    default:
      - "UKSouth"
      - "UKWest"
  - name: appSettingsEnv
    type: object
    default: []
  - name: runSonarScan
    type: boolean
    default: true
  - name: sonarExclusionPaths
    type: string
    default: ""

resources:
  repositories:
    - repository: DEFRA-ADPPipelineCommon
      name: DEFRA/adp-pipeline-common
      endpoint: DEFRA
      type: github
      ref: refs/heads/main

stages:
  - stage: Validate
    pool:
      name: DEFRA-COMMON-ubuntu2004-SSV3
    jobs:
      - job: Build
        steps:
        extends:
        - template: /templates/steps/nodejs-build.yaml@DEFRA-ADPPipelineCommon
          parameters:
            frameworkVersion: 6.x
            failOnThreshold: high
            packageFeedName: defra-devops-common
