parameters:
- name: forceDevDeploy
  displayName: Force deployment to DEV
  type: boolean
  default: false
- name: environments
  type: object
  default:
  - "dev"
  - "snd"
  - "pre"
  - "prd"
- name: deployToSecondary
  type: string
  default: ""
- name: azureRegions
  type: object
  default:
  - "UKSouth"
  - "UKWest"
- name: appSettingsEnv
  type: object
  default: []
- name: runSonarScan
  type: boolean
  default: true
- name: sonarExclusionPaths
  type: string
  default: ""

stages:
  - stage: Validate
    pool:
      name: DEFRA-COMMON-ubuntu2004-SSV3
    jobs:
      - job: Build
        steps:
          - checkout: self
            clean: true
            fetchTags: false

          - task: NodeTool@0
            displayName: 'Use Node 6.x '
            inputs:
              versionSpec: 6.x
              checkLatest: true 
            enabled: true #this step takes long time to download nodejs file  

          - bash: |
              echo "##vso[task.setvariable variable=COOKIE_PASSWORD;]$RANDOM"
            displayName: 'Generate Random COOKIE_PASSWORD for test'

          - task: Npm@1
            displayName: 'npm ci'
            inputs:
              command: custom
              customCommand: 'ci --legacy-peer-deps'
              verbose: false
              customRegistry: useFeed
              customFeed: defra-devops-common
                    
          - task: Npm@1
            displayName: 'npm audit'
            inputs:
              command: custom
              verbose: false
              customCommand: 'audit -audit-level=high --omit=dev' 
            continueOnError: ${{ ne(variables['Build.Reason'], 'PullRequest') }}

          - task: Npm@1
            displayName: 'npm lint'
            inputs:
              command: custom
              verbose: false
              customCommand: 'run --if-present test:lint'
            continueOnError: ${{ ne(variables['Build.Reason'], 'PullRequest') }}

          - task: Npm@1
            displayName: 'npm build'
            inputs:
              command: custom
              verbose: false
              customCommand: 'run --if-present build'

          - task: Npm@1
            displayName: 'npm unit test'
            inputs:
              command: custom
              verbose: false
              customCommand: 'run --if-present test:unit'