#!/bin/bash
echo "waiting for db $SQL_HOST:$SQL_PORT"
response=''
max_tries=15
count=0
while :
do
  ((count++))
  if [ "$count" -ge "$max_tries" ]; then
    echo "db did not respond in time"
    exit 1
  fi
  response=$(wget -SO- -T 1 -t 1 http://$SQL_HOST:$SQL_PORT 2>&1 | grep 'No data received')
  if [ "$response" ]; then
    echo "db server available"
    break
  fi
  printf '.'
  sleep 2
done
echo db started
